name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Restore Gatsby cache
        uses: actions/cache@v4
        with:
          path: |
            .cache
            public
          key: ${{ runner.os }}-gatsby-20-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-gatsby-20-

      - name: Lint
        run: npm run lint --silent

      - name: Build
        run: npm run build --silent
