name: Linter
on:
  pull_request:
    branches: [ master ]
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Lint
      run: |
        npm install
        npm run lint