name: Linter
on:
  pull_request:
    branches: [ master ]
jobs:
  linter:
    name: "Check on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - uses: actions/setup-node@v6
      with:
        node-version: '20'

    - name: Lint
      run: |
        npm install
        npm run lint
    
    - name: Build
      run: npm run build
