name: Staging

on:
  pull_request_target:
    types: [opened, synchronize, edited, reopened]
    branches: [ master ]

jobs:
  staging:
    name: Blog Staging
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with:
        path: gh-actions
        fetch-depth: 0

    - name: Setup branch
      run: |
        GIT_REMOTE_REF=refs/pull/$PR_NUMBER/head
        cd gh-actions
        git fetch origin $GIT_REMOTE_REF:testBranch
        git checkout testBranch
      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}

    - uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Install Gatsby CLI
      run: npm install -g gatsby-cli

    - name: Build
      run: |
        gh-actions
        npm install
        npm run build

    - name: Setup git config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"

    - name: Checkout Staging repo
      uses: actions/checkout@v2
      with:
        repository: AdoptOpenJDK/staging-blog
        path: staging-blog
        token: ${{ secrets.ACCESS_TOKEN }}
        ssh-key: ${{ secrets.ADOPT_BOT_SSH_PRIVATE }}

    - run: |
        if [[ ! -d "staging-blog/$PR_NUMBER" ]]; then
          mkdir staging-blog/$PR_NUMBER
        fi
        cp -R gh-actions/public/* staging-blog/$PR_NUMBER
        cd staging-blog
        git add .
        git commit -m "Staging $PR_NUMBER"
        git push origin gh-pages
      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}

    - uses: mshick/add-pr-comment@v1
      with:
        message: Now on staging server [here](https://staging-blog.adoptopenjdk.net/${{ env.PR_NUMBER }}).
        repo-token: ${{ secrets.ACCESS_TOKEN }}
        repo-token-user-login: 'adoptopenjdk-github-bot'
        allow-repeats: true
      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}
